name: Deploy FRONT to OVH

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy front folder to OVH
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr --delete
        path: ./front/
        remote_path: /home/hemiapr/www/synthese/
        remote_host: ${{ secrets.FTP_HOST }}
        remote_user: ${{ secrets.FTP_USER }}
        remote_key: ${{ secrets.SSH_KEY }}
